# _config.yml  (abridged)

title: "Shadi Rahimfallah"
url: "https://shadirahimfallah.github.io"
baseurl: ""
repository: "ShadiRahimfallah/ShadiRahimfallah.github.io"

# Tell Jekyll to build files in /_pages
include:
  - _pages






author:
  avatar     : "https://shadirahimfallah.github.io/images/shadi.jpg"    # file must exist
  name       : "Shadi Rahimfallah"
  pronouns   : "she/her"
  bio        : "PhD student, Department of Economics, York University."
  location   : "Toronto, Canada"
  #employer  : "York University"
  email      : "shadirf[a]yorku.ca"
  # Social/link icons shown in the sidebar:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:shadirf@yorku.ca"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ShadiRahimfallah"
    # add LinkedIn/Twitter if you like
  

