author:
  avatar     : "/images/shadi.jpg"     # file must exist
  name       : "Shadi Rahimfallah"
  pronouns   : "she/her"
  bio        : "PhD student, Department of Economics, York University."
  location   : "Toronto, Canada"
  #employer  : "York University"
  email      : "shadirf@yorku.ca"
  # Social/link icons shown in the sidebar:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:shadi.rahimfallah@gmail.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ShadiRahimfallah"
    # add LinkedIn/Twitter if you like
